# # vim: ft=tmux
set -g status "on"
set -g status-interval 1
set -g status-left-length "100"
set -g status-right-length "100"

set -g base-index 1
set -g renumber-windows on
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#{b:pane_current_path}#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#{b:pane_current_path}#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
