# vim: ft=tmux
set -g status "on"
set -g status-interval 1
set -g status-left-length "100"
set -g status-right-length "100"

set -g base-index 1
set -g renumber-windows on
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=default"

# active pane colors
set -g pane-border-style "fg=colour238"
# set -g pane-active-border-style "fg=colour250"

set -g @online_icon "ok"
set -g @offline_icon "nok"


# status left look and feel
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg}]#{?#{==:#{online_status},ok},#[fg=#{@thm_rosewater}] 󰖩 on ,#[fg=#{@thm_red}]#[reverse] 󰖪 off }"

set -g window-status-current-style "fg=black bg=white"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#{b:pane_current_path}#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#{b:pane_current_path}#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
